# GApps dependencies
PRODUCT_COPY_FILES += \
vendor/google/products/proprietary/system/usr/srec/en-US/grammar.config:system/usr/srec/en-US/grammar.config:google \
vendor/google/products/proprietary/system/usr/srec/en-US/hotword_word_symbols:system/usr/srec/en-US/hotword_word_symbols:google \
vendor/google/products/proprietary/system/usr/srec/en-US/normalizer:system/usr/srec/en-US/normalizer:google \
vendor/google/products/proprietary/system/usr/srec/en-US/metadata:system/usr/srec/en-US/metadata:google \
vendor/google/products/proprietary/system/usr/srec/en-US/endpointer_dictation.config:system/usr/srec/en-US/endpointer_dictation.config:google \
vendor/google/products/proprietary/system/usr/srec/en-US/rescoring_lm:system/usr/srec/en-US/rescoring_lm:google \
vendor/google/products/proprietary/system/usr/srec/en-US/norm_fst:system/usr/srec/en-US/norm_fst:google \
vendor/google/products/proprietary/system/usr/srec/en-US/hclg_shotword:system/usr/srec/en-US/hclg_shotword:google \
vendor/google/products/proprietary/system/usr/srec/en-US/endpointer_voicesearch.config:system/usr/srec/en-US/endpointer_voicesearch.config:google \
vendor/google/products/proprietary/system/usr/srec/en-US/clg:system/usr/srec/en-US/clg:google \
vendor/google/products/proprietary/system/usr/srec/en-US/dict:system/usr/srec/en-US/dict:google \
vendor/google/products/proprietary/system/usr/srec/en-US/hotword_prompt.txt:system/usr/srec/en-US/hotword_prompt.txt:google \
vendor/google/products/proprietary/system/usr/srec/en-US/offensive_word_normalizer:system/usr/srec/en-US/offensive_word_normalizer:google \
vendor/google/products/proprietary/system/usr/srec/en-US/dictation.config:system/usr/srec/en-US/dictation.config:google \
vendor/google/products/proprietary/system/usr/srec/en-US/phonelist:system/usr/srec/en-US/phonelist:google \
vendor/google/products/proprietary/system/usr/srec/en-US/wordlist:system/usr/srec/en-US/wordlist:google \
vendor/google/products/proprietary/system/usr/srec/en-US/phone_state_map:system/usr/srec/en-US/phone_state_map:google \
vendor/google/products/proprietary/system/usr/srec/en-US/hmm_symbols:system/usr/srec/en-US/hmm_symbols:google \
vendor/google/products/proprietary/system/usr/srec/en-US/hotword_normalizer:system/usr/srec/en-US/hotword_normalizer:google \
vendor/google/products/proprietary/system/usr/srec/en-US/g2p_fst:system/usr/srec/en-US/g2p_fst:google \
vendor/google/products/proprietary/system/usr/srec/en-US/contacts.abnf:system/usr/srec/en-US/contacts.abnf:google \
vendor/google/products/proprietary/system/usr/srec/en-US/compile_grammar.config:system/usr/srec/en-US/compile_grammar.config:google \
vendor/google/products/proprietary/system/usr/srec/en-US/c_fst:system/usr/srec/en-US/c_fst:google \
vendor/google/products/proprietary/system/usr/srec/en-US/commands.abnf:system/usr/srec/en-US/commands.abnf:google \
vendor/google/products/proprietary/system/usr/srec/en-US/hotword.config:system/usr/srec/en-US/hotword.config:google \
vendor/google/products/proprietary/system/usr/srec/en-US/hotword_classifier:system/usr/srec/en-US/hotword_classifier:google \
vendor/google/products/proprietary/system/usr/srec/en-US/ep_acoustic_model:system/usr/srec/en-US/ep_acoustic_model:google \
vendor/google/products/proprietary/system/usr/srec/en-US/dnn:system/usr/srec/en-US/dnn:google \
vendor/google/products/proprietary/system/usr/srec/en-US/hmmlist:system/usr/srec/en-US/hmmlist:google \
vendor/google/products/proprietary/system/app/GoogleContactsSyncAdapter.apk:system/app/GoogleContactsSyncAdapter.apk:google \
vendor/google/products/proprietary/system/app/PlayGames.apk:system/app/PlayGames.apk:google \
vendor/google/products/proprietary/system/app/Music2.apk:system/app/Music2.apk:google \
vendor/google/products/proprietary/system/app/Magazines.apk:system/app/Magazines.apk:google \
vendor/google/products/proprietary/system/app/MediaUploader.apk:system/app/MediaUploader.apk:google \
vendor/google/products/proprietary/system/app/Street.apk:system/app/Street.apk:google \
vendor/google/products/proprietary/system/app/Gmail2.apk:system/app/Gmail2.apk:google \
vendor/google/products/proprietary/system/app/Videos.apk:system/app/Videos.apk:google \
vendor/google/products/proprietary/system/app/FaceLock.apk:system/app/FaceLock.apk:google \
vendor/google/products/proprietary/system/app/YouTube.apk:system/app/YouTube.apk:google \
vendor/google/products/proprietary/system/app/Drive.apk:system/app/Drive.apk:google \
vendor/google/products/proprietary/system/app/GoogleCalendarSyncAdapter.apk:system/app/GoogleCalendarSyncAdapter.apk:google \
vendor/google/products/proprietary/system/app/LatinImeGoogle.apk:system/app/LatinImeGoogle.apk:google \
vendor/google/products/proprietary/system/app/Maps.apk:system/app/Maps.apk:google \
vendor/google/products/proprietary/system/app/CloudPrint.apk:system/app/CloudPrint.apk:google \
vendor/google/products/proprietary/system/app/Books.apk:system/app/Books.apk:google \
vendor/google/products/proprietary/system/app/talkback.apk:system/app/talkback.apk:google \
vendor/google/products/proprietary/system/priv-app/GoogleBackupTransport.apk:system/priv-app/GoogleBackupTransport.apk:google \
vendor/google/products/proprietary/system/priv-app/ConfigUpdater.apk:system/priv-app/ConfigUpdater.apk:google \
vendor/google/products/proprietary/system/priv-app/Velvet.apk:system/priv-app/Velvet.apk:google \
vendor/google/products/proprietary/system/priv-app/GoogleLoginService.apk:system/priv-app/GoogleLoginService.apk:google \
vendor/google/products/proprietary/system/priv-app/GmsCore.apk:system/priv-app/GmsCore.apk:google \
vendor/google/products/proprietary/system/priv-app/GoogleServicesFramework.apk:system/priv-app/GoogleServicesFramework.apk:google \
vendor/google/products/proprietary/system/priv-app/GoogleFeedback.apk:system/priv-app/GoogleFeedback.apk:google \
vendor/google/products/proprietary/system/priv-app/Phonesky.apk:system/priv-app/Phonesky.apk:google \
vendor/google/products/proprietary/system/priv-app/SetupWizard.apk:system/priv-app/SetupWizard.apk:google \
vendor/google/products/proprietary/system/priv-app/GooglePartnerSetup.apk:system/priv-app/GooglePartnerSetup.apk:google \
vendor/google/products/proprietary/system/etc/updatecmds/google_generic_update.txt:system/etc/updatecmds/google_generic_update.txt:google \
vendor/google/products/proprietary/system/etc/permissions/com.google.android.maps.xml:system/etc/permissions/com.google.android.maps.xml:google \
vendor/google/products/proprietary/system/etc/permissions/com.google.android.media.effects.xml:system/etc/permissions/com.google.android.media.effects.xml:google \
vendor/google/products/proprietary/system/vendor/media/PFFprec_600.emd:system/vendor/media/PFFprec_600.emd:google \
vendor/google/products/proprietary/system/vendor/media/LMspeed_508.emd:system/vendor/media/LMspeed_508.emd:google \
vendor/google/products/proprietary/system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32.bin:google \
vendor/google/products/proprietary/system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32.bin:google \
vendor/google/products/proprietary/system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2.bin:system/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2.bin:google \
vendor/google/products/proprietary/system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24.bin:google \
vendor/google/products/proprietary/system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24.bin:google \
vendor/google/products/proprietary/system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24.bin:system/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24.bin:google \
vendor/google/products/proprietary/system/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N.bin:system/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N.bin:google \
vendor/google/products/proprietary/system/framework/com.google.android.maps.jar:system/framework/com.google.android.maps.jar:google \
vendor/google/products/proprietary/system/framework/com.google.android.media.effects.jar:system/framework/com.google.android.media.effects.jar:google \
vendor/google/products/proprietary/system/lib/libAppDataSearch.so:system/lib/libAppDataSearch.so:google \
vendor/google/products/proprietary/system/lib/libexif_jni.so:system/lib/libexif_jni.so:google \
vendor/google/products/proprietary/system/lib/libcrashreporter.so:system/lib/libcrashreporter.so:google \
vendor/google/products/proprietary/system/lib/libgoogle_hotword_jni.so:system/lib/libgoogle_hotword_jni.so:google \
vendor/google/products/proprietary/system/lib/libgmscore.so:system/lib/libgmscore.so:google \
vendor/google/products/proprietary/system/lib/libgoogle_recognizer_jni_l.so:system/lib/libgoogle_recognizer_jni_l.so:google \
vendor/google/products/proprietary/system/lib/libfrsdk.so:system/lib/libfrsdk.so:google \
vendor/google/products/proprietary/system/lib/libgmm-jni.so:system/lib/libgmm-jni.so:google \
vendor/google/products/proprietary/system/lib/libconscrypt_gmscore_jni.so:system/lib/libconscrypt_gmscore_jni.so:google \
vendor/google/products/proprietary/system/lib/libfacelock_jni.so:system/lib/libfacelock_jni.so:google \
vendor/google/products/proprietary/system/lib/libfilterpack_facedetect.so:system/lib/libfilterpack_facedetect.so:google \
vendor/google/products/proprietary/system/lib/librectifier.so:system/lib/librectifier.so:google \
vendor/google/products/proprietary/system/lib/libjni_unbundled_latinimegoogle.so:system/lib/libjni_unbundled_latinimegoogle.so:google \
vendor/google/products/proprietary/system/lib/libvcdecoder_jni.so:system/lib/libvcdecoder_jni.so:google \
vendor/google/products/proprietary/system/lib/libgames_rtmp_jni.so:system/lib/libgames_rtmp_jni.so:google \
vendor/google/products/proprietary/system/lib/libdocsimageutils.so:system/lib/libdocsimageutils.so:google \
vendor/google/products/proprietary/system/lib/libWVphoneAPI.so:system/lib/libWVphoneAPI.so:google \
vendor/google/products/proprietary/system/lib/libdocscanner_image.so:system/lib/libdocscanner_image.so:google \

PRODUCT_PACKAGES += \
GoogleContactsSyncAdapter \
PlayGames \
Music2 \
Magazines \
MediaUploader \
Street \
Gmail2 \
Videos \
FaceLock \
YouTube \
Drive \
GoogleCalendarSyncAdapter \
LatinImeGoogle \
Maps \
CloudPrint \
Books \
talkback \
GoogleBackupTransport \
ConfigUpdater \
Velvet \
GoogleLoginService \
GmsCore \
GoogleServicesFramework \
GoogleFeedback \
Phonesky \
SetupWizard \
GooglePartnerSetup \
